//
//  PlanetViewModel.swift
//  AstroArena
//
//  Created by Alessandro Ricci on 21/02/24.
//

import Foundation

class PlanetViewModel: ObservableObject{
    
    var planets: [Planet] = [
        
        Planet(planetCard: "c1", planetName: "THE SUN", fileName: "SunAstroArena.usdz", planetDetails: "The Sun is the star at the center of our solar system, around which the planets, including Earth, orbit. It is a glowing ball of gas, mainly composed of hydrogen and helium, which produces energy through nuclear fusion processes. This energy is radiated into space in the form of light and heat. The Sun is incredibly large, with a diameter of about 1.4 million kilometers, and accounts for about 99.8 percent of the total mass of the solar system. Its surface temperature is about 5,500 degrees Celsius, while at its core it can reach temperatures in excess of 15 million degrees Celsius. Light from the Sun provides vital energy for life on Earth through the process of photosynthesis, which enables plants to produce oxygen and create food. The Sun has a solar activity cycle that lasts about 11 years, characterized by variations in the number of sunspots and solar flares. Studying the Sun is critical to understanding the mechanisms that drive climate and energy in our solar system, as well as to better understand stars and their life cycles in the universe."),
        Planet(planetCard: "c2", planetName: "MERCURY", fileName: "MercuryAstroArena.usdz", planetDetails: "Mercury is the innermost planet in the solar system and the closest to the Sun. It is a small, rocky planet with a diameter of about 4,880 kilometers, slightly larger than the Moon. Because of its proximity to the Sun, Mercury has an extremely variable surface temperature, which can reach 427 degrees Celsius during the day and drop to -173 degrees Celsius at night. Mercury has a surface characterized by craters caused by meteor impacts, steep escarpments and lava plains. Despite being so close to the Sun, Mercury does not have a significant atmosphere, and its thin atmosphere is mainly composed of helium, with traces of oxygen and sodium. The planet has been visited by only one space mission, NASA's Messenger, which provided valuable information about its composition, geological structure and magnetic field. Mercury is an object of great interest to scientists seeking to better understand the formation and evolution of rocky planets in the solar system."),
        Planet(planetCard: "c3", planetName: "VENUS", fileName: "VenusAstroArena.usdz", planetDetails: "Venus is the second planet in the solar system, located between Mercury and Earth. It is often called the twin planet of Earth because of their similar size, but the similarities stop there. Venus is a hellish world with an extremely high surface temperature of up to 470 degrees Celsius, enough to melt lead. This makes it the hottest planet in the solar system, despite not being the closest to the Sun. Its dense atmosphere is composed mainly of carbon dioxide, with clouds of sulfuric acid covering the surface. Venus rotates slowly on itself in the opposite direction to most planets in the solar system, in a phenomenon called retrograde rotation. Its surface is characterized by volcanoes, craters and lava plains, suggesting a volcanically active past. Venus has no moons, and its atmosphere creates an extreme greenhouse effect that contributes to its hellish climate. Despite the prohibitive conditions, Venus has been the subject of several space missions, which have contributed to a better understanding of its geology, atmosphere and evolutionary history."),
        Planet(planetCard: "c4", planetName: "EARTH & MOON", fileName: "EarthAstroArena.usdz" + "MoonAstroArena.usdz", planetDetails: "Earth is the third planet in the solar system and the only planet known to harbor life. It has a wide range of environments, including land, oceans and atmosphere that support a wide variety of life forms. Earth has an oxygen-rich atmosphere, which is essential for life as we know it. The Moon is Earth's natural satellite and is the fifth largest satellite in the solar system. It is a very close object to Earth, making it a celestial object clearly visible to us on Earth. The Moon has no atmosphere and its surface is characterized by craters, mountains, valleys and lunar seas. The Moon has played a significant role in human history, inspiring myths, legends and contributing to the development of science and space exploration."),
        Planet(planetCard: "c5", planetName: "MARS", fileName: "MarsAstroArena.usdz", planetDetails: "Mars is the fourth planet in the solar system, located between Earth and Jupiter. It is often called the Red Planet because of the distinctive color of its surface, due to the presence of iron oxide, or rust. Mars is smaller than Earth, with a surface characterized by canyons, extinct volcanoes and plains. The highest mountain in the solar system, Mount Olympus, is located on Mars. Mars has two small natural satellites, Phobos and Deimos. Its atmosphere is very thin and composed mainly of carbon dioxide. Despite the planet's extreme temperatures and drought, there is evidence of ancient environmental conditions that may have supported microbial life. Mars has been the subject of intense research and interest in human and robotic exploration, with numerous space missions sent to study the planet and look for signs of past or present life."),
        Planet(planetCard: "c6", planetName: "JUPITER", fileName: "JupiterAstroArena.usdz", planetDetails: "Jupiter is the fifth planet in the solar system and the largest of all, with a mass more than two and a half times that of all the other planets combined. It is mainly composed of hydrogen and helium, with a small amount of other elements. Jupiter is famous for its Great Red Spot, a giant storm that lasts at least 400 years. The planet has a vast array of moons, with more than 80 natural satellites confirmed so far. Four of these larger moons - Io, Europa, Ganymede and Callisto - are known as Galilean moons and are among the most interesting celestial bodies in the outer solar system. Jupiter is also surrounded by a system of rings, although they are much fainter and less distinct than Saturn's rings. Its massive gravity has a significant influence on the solar system, disrupting the orbits of other planets and asteroids. It is the subject of intense research both through robotic exploration, with missions such as the Juno probe, and through observations from telescopes on Earth and in space."),
        Planet(planetCard: "c7", planetName: "SATURN", fileName: "SaturnAstroArena.usdz", planetDetails: "Saturn is the sixth planet in the solar system, and is known for its distinctive bright rings, making it one of the most recognizable planets. It is a gas giant, mainly composed of hydrogen and helium, with a dense atmosphere and a mass about 95 times that of Earth. Saturn's rings consist mainly of ice and rock fragments, extending thousands of kilometers into space. These rings are divided into several concentric bands and have been the subject of intense research and study. Saturn also has a number of moons, with more than 80 natural satellites confirmed so far. Of these, the largest moon, Titan, is particularly interesting because it has a dense atmosphere and geological features similar to those of Earth. The planet has a system of atmospheric storms and eddies, but they are not as evident as on Jupiter's surface. It has been visited by several space missions, including the Cassini-Huygens probe, which provided a vast amount of data and detailed images of the planet, its rings and moons."),
        Planet(planetCard: "c8", planetName: "URANUS", fileName: "UranusAstroArena.usdz", planetDetails: "Uranus is the seventh planet in the solar system, and is an icy giant, similar to Neptune. It is known for its tilted position and lying down rotational motion, which makes it unique among the planets of the solar system. This planet is mainly composed of hydrogen and helium, with a small percentage of water ice and ammonia in its atmosphere. Uranus has a series of rings, although they are less distinct and visible than those of Saturn. It also has a number of moons, including Miranda, Umbriel, Titania and Oberon, among the largest. Miranda, in particular, has a very varied surface with ridges, canyons and other unique features. Uranus has only been visited by one space probe, Voyager 2 in 1986, which provided limited but valuable information about the planet and its system of moons. However, it is still a subject of study and interest to researchers seeking to better understand its atmosphere, internal structure and origins."),
        Planet(planetCard: "c9", planetName: "NEPTUNE", fileName: "NeptuneAstroArena.usdz", planetDetails: "Neptune is the outermost of the gas giants in the solar system, and is the farthest planet from the Sun. It is a cold and windy planet, mainly composed of hydrogen and helium, with a small percentage of water ice and ammonia in its atmosphere. Neptune is known for its extremely fast winds, which can exceed 1,500 kilometers per hour, and for its Great Dark Spot, a huge storm similar to Jupiter's Great Red Spot. The planet has a system of rings, although they are very faint and less distinct than those on Saturn. It also has a number of moons, including Triton, Neptune's largest natural satellite, which is particularly interesting because it orbits the planet in a retrograde direction, suggesting that it may be a celestial body captured in the past. Neptune has been visited only once by a space probe, Voyager 2, in 1989, which provided a wealth of data and detailed images of the planet and its system of moons. However, it still remains an object of study and interest to scientists seeking to better understand its atmosphere, internal structure and origins."),
    ]



    
    
    
    
}

    
   
